version: '3.3'

networks:
  dbnet:

services:
  superset:
    image: apache/superset
    network_mode: "host"
    container_name: "superset-bigdata"
    env_file:
      - .dockerfile.env
    environment:
      DB_HOST: postgresdb
    ports:
      - "8088:8088"
