version: '3.3'

networks:
  dbnet:

services:
  postgresdb:
    container_name: "postgres-bigdata"
    image: postgres
    networks:
      - dbnet 
    env_file:
      - .dockerfile.env
  superset:
    image: apache/superset
    networks:
      - dbnet
    container_name: "superset-bigdata"
    depends_on:
      - postgresdb
    env_file:
      - .dockerfile.env
    environment:
      DB_HOST: postgresdb
    ports:
      - "8088:8088"
