version: '3.3'

services:
  kafka:
    build:
      context: ./container/.
      dockerfile: Kafka
    ports:
      - "9092:9092"
  superset:
    build:
      context: ./container/.
      dockerfile: Superset
    tty: true
    network_mode: "host"
    ports:
      - "8088:8088"

    
